In [19]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/SOC/Data/AgEvidence/tillage.csv')
df

,review,rv,rvYear,rvUnits,startYear,studyLength,sampleDepth,controlValue,trtValue,percentChange,...,treatment,sampledepth,doi,title,authors,authors_abbrev,pubyear,journal,volume_issue,pages
0,Tillage,soil organic carbon by weight mid-season,1,g/100 g,1989,4,0-30 cm,1.08,1.53,41.67,...,Conservation tillage,0-30 cm,10.1080/00103629409369033,Tillage effects on selected chemical propertie...,"Kitur, B.K., Phillips, S.R., Olson, K.R., & Eb...",Kitur et al.,1994,Communications in Soil Science and Plant Analysis,25,225-246
1,Tillage,soil organic carbon by weight mid-season,2,g/100 g,1989,4,0-30 cm,1.15,1.56,35.65,...,Conservation tillage,0-30 cm,10.1080/00103629409369033,Tillage effects on selected chemical propertie...,"Kitur, B.K., Phillips, S.R., Olson, K.R., & Eb...",Kitur et al.,1994,Communications in Soil Science and Plant Analysis,25,225-246
2,Tillage,soil organic carbon by weight mid-season,3,g/100 g,1989,4,0-30 cm,1.21,1.54,27.27,...,Conservation tillage,0-30 cm,10.1080/00103629409369033,Tillage effects on selected chemical propertie...,"Kitur, B.K., Phillips, S.R., Olson, K.R., & Eb...",Kitur et al.,1994,Communications in Soil Science and Plant Analysis,25,225-246
3,Tillage,soil organic carbon by weight mid-season,4,g/100 g,1989,4,0-30 cm,1.28,1.52,18.75,...,Conservation tillage,0-30 cm,10.1080/00103629409369033,Tillage effects on selected chemical propertie...,"Kitur, B.K., Phillips, S.R., Olson, K.R., & Eb...",Kitur et al.,1994,Communications in Soil Science and Plant Analysis,25,225-246
4,Tillage,soil organic carbon by weight mid-season,1,g/100 g,1989,4,0-30 cm,1.08,1.75,62.04,...,No tillage,0-30 cm,10.1080/00103629409369033,Tillage effects on selected chemical propertie...,"Kitur, B.K., Phillips, S.R., Olson, K.R., & Eb...",Kitur et al.,1994,Communications in Soil Science and Plant Analysis,25,225-246
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1583,Tillage,fertilizer induced emission factor,40,%,1975,41,NaN,0.32,0.45,0.13,...,No tillage,Not measured,10.2134/jeq2018.05.0188,Tillage and nitrogen source impacts on relatio...,"Omonode, R.E. & Vyn, T.J.",Omonode & Vyn,2019,Journal of Environmental Quality,48,421-429
1584,Tillage,fertilizer induced emission factor,41,%,1975,41,NaN,0.78,0.91,0.13,...,Conservation tillage,Not measured,10.2134/jeq2018.05.0188,Tillage and nitrogen source impacts on relatio...,"Omonode, R.E. & Vyn, T.J.",Omonode & Vyn,2019,Journal of Environmental Quality,48,421-429
1585,Tillage,fertilizer induced emission factor,41,%,1975,41,NaN,0.78,0.54,-0.24,...,Zonal tillage,Not measured,10.2134/jeq2018.05.0188,Tillage and nitrogen source impacts on relatio...,"Omonode, R.E. & Vyn, T.J.",Omonode & Vyn,2019,Journal of Environmental Quality,48,421-429
1586,Tillage,fertilizer induced emission factor,41,%,1975,41,NaN,0.78,0.84,0.06,...,No tillage,Not measured,10.2134/jeq2018.05.0188,Tillage and nitrogen source impacts on relatio...,"Omonode, R.E. & Vyn, T.J.",Omonode & Vyn,2019,Journal of Environmental Quality,48,421-429
1587,Tillage,greenhouse gas intensity (N~2~O/grain),10;11;12;13;14,kg N~2~O/Mg DM grain,2002,14,NaN,0.36,0.30,-16.67,...,No tillage,Not measured,10.1111/gcb.13637,Long-term no-till and stover retention each de...,"Jin, V.L., Schmer, M.R., Stewart, C.E., Sindel...",Jin et al.,2017,Global Change Biology,23(7),2848-2862

In [20]:
df.rv = df.rv.str.lower()

In [21]:
df = df.query('rv.str.contains("soil") and rv.str.contains("organic") and rv.str.contains("carbon") and not rv.str.contains("poc") and not rv.str.contains("particulate")', engine='python')

In [22]:
df.rv.value_counts()

soil organic carbon stock averaged across three crop rotations    252
soil organic carbon concentration                                 209
soil organic carbon reserves                                       81
total soil organic carbon                                          78
soil organic carbon                                                78
soil organic carbon content                                        60
soil total organic carbon                                          24
cumulative stock of soil organic carbon                            24
soil organic carbon by weight mid-season                           24
soil organic carbon concentration in spring                        24
soil organic carbon stocks                                         20
change in soil organic carbon concentrations                       18
soil organic carbon storage in the spring                          16
soil organic carbon concentration on an area basis                 12
soil organic carbon concentration on a mass basis                  10
mass of soil organic carbon                                         7
soil organic carbon on area basis                                   6
soil organic carbon stock                                           4
weighted soil organic carbon                                        4
soil organic carbon pool, c3                                        4
soil organic carbon pool, c4                                        4
total soil organic carbon pool in soil                              4
soil organic carbon pool                                            4
soil organic carbon in march                                        4
soil organic carbon contents                                        4
half-life of c-soil organic carbon                                  4
soil organic carbon, initial soc content                            3
soil organic carbon derived from corn root and shoot biomass        2
soil organic carbon storage after harvest                           2
soil organic carbon derived from corn root biomass                  2
soil organic carbon concentration (after harvest                    2
soil organic carbon content in wooster silt loam after harvest      2
soil organic carbon content in crosby silt loam after harvest       2
equivalent mass of soil organic carbon                              1
soil organic carbon stock (c3-c) in topsoil                         1
Name: rv, dtype: int64

In [23]:
df.rvUnits.value_counts()

Mg/ha               500
g/kg                181
g C/kg              121
Mg C/ha              81
g C/kg soil          28
g/100 g              24
Mg C/ha in depth     20
%                    18
g/kg soil             9
t/ha                  8
kg/m^2^               4
kg C/ha               1
kg/ha                 1
Name: rvUnits, dtype: int64

In [24]:
feature_cols = [
    "control",
    "treatment",
    "sampleDepth",
    "studyLength",
    "startYear"
]

In [25]:
X = df[feature_cols]
y = df['percentChange']

In [26]:
X.isnull().sum()

control         0
treatment       0
sampleDepth    38
studyLength     0
startYear       0
dtype: int64

In [27]:
X.sampleDepth.value_counts()

0-30 cm     554
0-60 cm     353
0-100 cm     33
0-150 cm     18
Name: sampleDepth, dtype: int64

In [28]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()
to_encode = ["control", "treatment", "sampleDepth"]

X[to_encode] = encoder.fit_transform(X[to_encode])

/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:3678: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[col] = igetitem(value, i)

In [29]:
X

      control  treatment  sampleDepth  studyLength  startYear
0         0.0        0.0          2.0            4       1989
1         0.0        0.0          2.0            4       1989
2         0.0        0.0          2.0            4       1989
3         0.0        0.0          2.0            4       1989
4         0.0        1.0          2.0            4       1989
...       ...        ...          ...          ...        ...
1155      0.0        0.0          3.0           13       2002
1156      0.0        1.0          3.0           13       2002
1157      0.0        1.0          3.0           13       2002
1158      0.0        2.0          3.0           13       2002
1159      0.0        2.0          3.0           13       2002

[996 rows x 5 columns]

In [31]:
X.fillna(0, inplace = True)
X.isnull().sum()

/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:5176: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

control        0
treatment      0
sampleDepth    0
studyLength    0
startYear      0
dtype: int64

In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [33]:
assert len(X_train) == len(y_train)
assert len(X_test) == len(y_test)

In [43]:
from sklearn.tree import DecisionTreeRegressor

rf  = DecisionTreeRegressor()
rf.fit(X_train, y_train)

DecisionTreeRegressor()

In [44]:
preds = rf.predict(X_test)

In [45]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_test, preds, squared = False)

29.52827162865171

In [ ]:
from sklearn import tree
import matplotlib.pyplot as plt

plt.figure(figsize=(50,50))
tree.plot_tree(rf, fontsize = 10)

In [52]:
df.groupby(['control', 'treatment']).agg({'percentChange': ['mean']})

                                          percentChange
                                                   mean
control              treatment
Conventional tillage Conservation tillage      1.711301
                     No tillage               10.461808
                     Zonal tillage             6.381040