In [10]:
import pandas as pd
df_list = [pd.read_csv('/content/drive/MyDrive/SOC/Data/AgEvidence/tillage/tillage0.csv'),
           pd.read_csv('/content/drive/MyDrive/SOC/Data/AgEvidence/tillage/tillage1.csv'),
           pd.read_csv('/content/drive/MyDrive/SOC/Data/AgEvidence/tillage/tillage2.csv')]
df = pd.concat(df_list, axis = 0)
df

,review,rv,rvYear,rvUnits,startYear,studyLength,sampleDepth,controlValue,trtValue,percentChange,...,treatment,sampledepth,doi,title,authors,authors_abbrev,pubyear,journal,volume_issue,pages
0,Tillage,soil organic carbon by weight mid-season,1,g/100 g,1989,4,0-30 cm,1.08,1.53,41.67,...,Conservation tillage,0-30 cm,10.1080/00103629409369033,Tillage effects on selected chemical propertie...,"Kitur, B.K., Phillips, S.R., Olson, K.R., & Eb...",Kitur et al.,1994,Communications in Soil Science and Plant Analysis,25,225-246
1,Tillage,soil organic carbon by weight mid-season,2,g/100 g,1989,4,0-30 cm,1.15,1.56,35.65,...,Conservation tillage,0-30 cm,10.1080/00103629409369033,Tillage effects on selected chemical propertie...,"Kitur, B.K., Phillips, S.R., Olson, K.R., & Eb...",Kitur et al.,1994,Communications in Soil Science and Plant Analysis,25,225-246
2,Tillage,soil organic carbon by weight mid-season,3,g/100 g,1989,4,0-30 cm,1.21,1.54,27.27,...,Conservation tillage,0-30 cm,10.1080/00103629409369033,Tillage effects on selected chemical propertie...,"Kitur, B.K., Phillips, S.R., Olson, K.R., & Eb...",Kitur et al.,1994,Communications in Soil Science and Plant Analysis,25,225-246
3,Tillage,soil organic carbon by weight mid-season,4,g/100 g,1989,4,0-30 cm,1.28,1.52,18.75,...,Conservation tillage,0-30 cm,10.1080/00103629409369033,Tillage effects on selected chemical propertie...,"Kitur, B.K., Phillips, S.R., Olson, K.R., & Eb...",Kitur et al.,1994,Communications in Soil Science and Plant Analysis,25,225-246
4,Tillage,soil organic carbon by weight mid-season,1,g/100 g,1989,4,0-30 cm,1.08,1.75,62.04,...,No tillage,0-30 cm,10.1080/00103629409369033,Tillage effects on selected chemical propertie...,"Kitur, B.K., Phillips, S.R., Olson, K.R., & Eb...",Kitur et al.,1994,Communications in Soil Science and Plant Analysis,25,225-246
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,Tillage,yield-scaled nitrous oxide emissions,39,kg N/Mg,1975,41,NaN,231.30,214.00,-7.48,...,No tillage,Not measured,10.2134/jeq2018.05.0188,Tillage and nitrogen source impacts on relatio...,"Omonode, R.E. & Vyn, T.J.",Omonode & Vyn,2019,Journal of Environmental Quality,48,421-429
133,Tillage,yield-scaled nitrous oxide emissions,40,kg N/Mg,1975,41,NaN,203.50,244.83,20.31,...,No tillage,Not measured,10.2134/jeq2018.05.0188,Tillage and nitrogen source impacts on relatio...,"Omonode, R.E. & Vyn, T.J.",Omonode & Vyn,2019,Journal of Environmental Quality,48,421-429
134,Tillage,yield-scaled nitrous oxide emissions,41,kg N/Mg,1975,41,NaN,175.33,193.50,10.36,...,No tillage,Not measured,10.2134/jeq2018.05.0188,Tillage and nitrogen source impacts on relatio...,"Omonode, R.E. & Vyn, T.J.",Omonode & Vyn,2019,Journal of Environmental Quality,48,421-429
135,Tillage,fertilizer induced emission factor,40,%,1975,41,NaN,0.37,0.45,0.08,...,No tillage,Not measured,10.2134/jeq2018.05.0188,Tillage and nitrogen source impacts on relatio...,"Omonode, R.E. & Vyn, T.J.",Omonode & Vyn,2019,Journal of Environmental Quality,48,421-429
136,Tillage,fertilizer induced emission factor,41,%,1975,41,NaN,0.54,0.84,0.30,...,No tillage,Not measured,10.2134/jeq2018.05.0188,Tillage and nitrogen source impacts on relatio...,"Omonode, R.E. & Vyn, T.J.",Omonode & Vyn,2019,Journal of Environmental Quality,48,421-429

In [11]:
df.rv = df.rv.str.lower()

In [12]:
df = df.query('rv.str.contains("soil") and rv.str.contains("organic") and rv.str.contains("carbon") and not rv.str.contains("poc") and not rv.str.contains("particulate")', engine='python')

In [13]:
df.rv.value_counts()

soil organic carbon stock averaged across three crop rotations        378
soil organic carbon concentration                                     271
soil organic carbon                                                   179
total soil organic carbon                                             114
soil organic carbon reserves                                          108
soil organic carbon content                                            74
soil organic carbon by weight mid-season                               36
soil total organic carbon                                              36
cumulative stock of soil organic carbon                                36
soil organic carbon stocks                                             30
soil organic carbon concentration in spring                            24
change in soil organic carbon concentrations                           21
soil organic carbon storage in the spring                              16
soil organic carbon concentration on an area basis                     12
soil organic carbon stock                                              11
soil organic carbon, initial soc content                               11
soil organic carbon pool                                               10
soil organic carbon concentration on a mass basis                      10
mass of soil organic carbon                                             7
half-life of c-soil organic carbon                                      6
soil organic carbon pool, c3                                            6
organic carbon pool in soil                                             6
soil organic carbon in march                                            6
soil organic carbon on area basis                                       6
total soil organic carbon pool in soil                                  6
soil organic carbon pool, c4                                            6
weighted soil organic carbon                                            4
soil organic carbon contents                                            4
soil organic carbon derived from corn root and shoot biomass            3
c4-derived soil carbon accumulation, with organic fertilizer            3
soil organic carbon derived from corn root biomass                      3
c3-derived soil carbon accumulation, with organic fertilizer            3
soil organic carbon content in wooster silt loam after harvest          3
soil organic carbon content in crosby silt loam after harvest           3
soil organic carbon concentration (after harvest                        2
soil organic carbon storage after harvest                               2
soil organic carbon stock (c3-c) in topsoil                             1
soil organic carbon in mg/ha                                            1
soil organic carbon in g/kg                                             1
soil organic carbon of soil aggregate size 6-19 mm                      1
soil organic carbon of soil aggregate size 2.0-6.0 mm                   1
soil organic carbon of soil aggregate size 0.8-2.0 mm                   1
soil organic carbon of soil aggregate size 0.4-0.8 mm                   1
soil organic carbon of soil aggregate size >19 mm                       1
soil organic carbon of soil aggregate size <0.4 mm                      1
% soil organic carbon loss as flux (180 days during fallow period)      1
equivalent mass of soil organic carbon                                  1
Name: rv, dtype: int64

In [14]:
df.rvUnits.value_counts()

Mg/ha               782
g/kg                253
g C/kg              154
Mg C/ha             123
g/100 g              36
%                    30
g C/kg soil          28
Mg C/ha in depth     20
g/kg soil            17
t/ha                  8
kg/m^2^               7
Mg/kg                 6
kg C/ha               1
kg/ha                 1
SOC flux              1
Name: rvUnits, dtype: int64

Convert Units

In [15]:
# change all g/kg variants to g/kg
units = list(df.rvUnits)
for i in range(len(units)):
    if "/kg" in units[i]:
        units[i] = "g/kg"

# df.rvUnits = units
# df.rvUnits.value_counts()

In [16]:
# change to percent
control_values = list(df.controlValue)
for i in range(len(units)):
    # g/100 g and % are already in percent
    if units[i] == "g/kg":
        control_values[i] *= 0.1

# df.controlValue = control_values

In [17]:
df

,review,rv,rvYear,rvUnits,startYear,studyLength,sampleDepth,controlValue,trtValue,percentChange,...,treatment,sampledepth,doi,title,authors,authors_abbrev,pubyear,journal,volume_issue,pages
0,Tillage,soil organic carbon by weight mid-season,1,g/100 g,1989,4,0-30 cm,1.08,1.53,41.67,...,Conservation tillage,0-30 cm,10.1080/00103629409369033,Tillage effects on selected chemical propertie...,"Kitur, B.K., Phillips, S.R., Olson, K.R., & Eb...",Kitur et al.,1994,Communications in Soil Science and Plant Analysis,25,225-246
1,Tillage,soil organic carbon by weight mid-season,2,g/100 g,1989,4,0-30 cm,1.15,1.56,35.65,...,Conservation tillage,0-30 cm,10.1080/00103629409369033,Tillage effects on selected chemical propertie...,"Kitur, B.K., Phillips, S.R., Olson, K.R., & Eb...",Kitur et al.,1994,Communications in Soil Science and Plant Analysis,25,225-246
2,Tillage,soil organic carbon by weight mid-season,3,g/100 g,1989,4,0-30 cm,1.21,1.54,27.27,...,Conservation tillage,0-30 cm,10.1080/00103629409369033,Tillage effects on selected chemical propertie...,"Kitur, B.K., Phillips, S.R., Olson, K.R., & Eb...",Kitur et al.,1994,Communications in Soil Science and Plant Analysis,25,225-246
3,Tillage,soil organic carbon by weight mid-season,4,g/100 g,1989,4,0-30 cm,1.28,1.52,18.75,...,Conservation tillage,0-30 cm,10.1080/00103629409369033,Tillage effects on selected chemical propertie...,"Kitur, B.K., Phillips, S.R., Olson, K.R., & Eb...",Kitur et al.,1994,Communications in Soil Science and Plant Analysis,25,225-246
4,Tillage,soil organic carbon by weight mid-season,1,g/100 g,1989,4,0-30 cm,1.08,1.75,62.04,...,No tillage,0-30 cm,10.1080/00103629409369033,Tillage effects on selected chemical propertie...,"Kitur, B.K., Phillips, S.R., Olson, K.R., & Eb...",Kitur et al.,1994,Communications in Soil Science and Plant Analysis,25,225-246
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,Tillage,soil organic carbon stock averaged across thre...,7,Mg/ha,2002,13,0-60 cm,156.70,156.70,0.00,...,No tillage,0-60 cm,10.1002/saj2.20003,Quantifying soil carbon change in a long-term ...,"Al-Kaisi, M.M., & Kwaw-Mensah, D.",Al-Kaisi & Kwaw-Mensah,2020,Soil Science Society of America Journal,84,182-202
92,Tillage,soil organic carbon stock averaged across thre...,9,Mg/ha,2002,13,0-60 cm,158.20,158.20,0.00,...,No tillage,0-60 cm,10.1002/saj2.20003,Quantifying soil carbon change in a long-term ...,"Al-Kaisi, M.M., & Kwaw-Mensah, D.",Al-Kaisi & Kwaw-Mensah,2020,Soil Science Society of America Journal,84,182-202
93,Tillage,soil organic carbon stock averaged across thre...,0,Mg/ha,2002,13,0-60 cm,158.86,158.86,0.00,...,No tillage,0-60 cm,10.1002/saj2.20003,Quantifying soil carbon change in a long-term ...,"Al-Kaisi, M.M., & Kwaw-Mensah, D.",Al-Kaisi & Kwaw-Mensah,2020,Soil Science Society of America Journal,84,182-202
94,Tillage,soil organic carbon stock averaged across thre...,11,Mg/ha,2002,13,0-60 cm,158.90,158.90,0.00,...,No tillage,0-60 cm,10.1002/saj2.20003,Quantifying soil carbon change in a long-term ...,"Al-Kaisi, M.M., & Kwaw-Mensah, D.",Al-Kaisi & Kwaw-Mensah,2020,Soil Science Society of America Journal,84,182-202
95,Tillage,soil organic carbon stock averaged across thre...,13,Mg/ha,2002,13,0-60 cm,159.30,159.30,0.00,...,No tillage,0-60 cm,10.1002/saj2.20003,Quantifying soil carbon change in a long-term ...,"Al-Kaisi, M.M., & Kwaw-Mensah, D.",Al-Kaisi & Kwaw-Mensah,2020,Soil Science Society of America Journal,84,182-202

In [18]:
df.columns

Index(['review', 'rv', 'rvYear', 'rvUnits', 'startYear', 'studyLength',
       'sampleDepth', 'controlValue', 'trtValue', 'percentChange', 'norm',
       'studyduration', 'control', 'treatment', 'sampledepth', 'doi', 'title',
       'authors', 'authors_abbrev', 'pubyear', 'journal', 'volume_issue',
       'pages'],
      dtype='object')

In [19]:
feature_cols = [
    "control",
    "rvUnits",
    "controlValue",
    "treatment",
    "sampleDepth",
    "studyLength",
    "startYear",
    "norm"
]

In [20]:
X = df[feature_cols]
y = df['percentChange']

In [21]:
X.isnull().sum()

control          0
rvUnits          0
controlValue     0
treatment        0
sampleDepth     56
studyLength      0
startYear        0
norm             0
dtype: int64

In [22]:
X.sampleDepth.value_counts()

0-30 cm     817
0-60 cm     506
0-100 cm     62
0-150 cm     26
Name: sampleDepth, dtype: int64

In [23]:
X

,control,rvUnits,controlValue,treatment,sampleDepth,studyLength,startYear,norm
0,Conventional tillage,g/100 g,1.08,Conservation tillage,0-30 cm,4,1989,2
1,Conventional tillage,g/100 g,1.15,Conservation tillage,0-30 cm,4,1989,2
2,Conventional tillage,g/100 g,1.21,Conservation tillage,0-30 cm,4,1989,2
3,Conventional tillage,g/100 g,1.28,Conservation tillage,0-30 cm,4,1989,2
4,Conventional tillage,g/100 g,1.08,No tillage,0-30 cm,4,1989,2
...,...,...,...,...,...,...,...,...
91,Zonal tillage,Mg/ha,156.70,No tillage,0-60 cm,13,2002,2
92,Zonal tillage,Mg/ha,158.20,No tillage,0-60 cm,13,2002,2
93,Zonal tillage,Mg/ha,158.86,No tillage,0-60 cm,13,2002,2
94,Zonal tillage,Mg/ha,158.90,No tillage,0-60 cm,13,2002,2
95,Zonal tillage,Mg/ha,159.30,No tillage,0-60 cm,13,2002,2

In [24]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()
to_encode = ["control", "treatment", "sampleDepth", "rvUnits"]

X[to_encode] = encoder.fit_transform(X[to_encode])

/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:3678: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[col] = igetitem(value, i)

In [25]:
X

,control,rvUnits,controlValue,treatment,sampleDepth,studyLength,startYear,norm
0,1.0,8.0,1.08,0.0,2.0,4,1989,2
1,1.0,8.0,1.15,0.0,2.0,4,1989,2
2,1.0,8.0,1.21,0.0,2.0,4,1989,2
3,1.0,8.0,1.28,0.0,2.0,4,1989,2
4,1.0,8.0,1.08,1.0,2.0,4,1989,2
...,...,...,...,...,...,...,...,...
91,2.0,3.0,156.70,1.0,3.0,13,2002,2
92,2.0,3.0,158.20,1.0,3.0,13,2002,2
93,2.0,3.0,158.86,1.0,3.0,13,2002,2
94,2.0,3.0,158.90,1.0,3.0,13,2002,2
95,2.0,3.0,159.30,1.0,3.0,13,2002,2

In [26]:
X.fillna(0, inplace = True)
X.isnull().sum()

/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:5176: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

control         0
rvUnits         0
controlValue    0
treatment       0
sampleDepth     0
studyLength     0
startYear       0
norm            0
dtype: int64

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [28]:
assert len(X_train) == len(y_train)
assert len(X_test) == len(y_test)

In [29]:
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor()
dt.fit(X_train, y_train)

DecisionTreeRegressor()

In [30]:
preds = dt.predict(X_test)

In [31]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_test, preds, squared = False)

29.571766176062642

In [32]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators = 500)
rf.fit(X_train, y_train)

RandomForestRegressor(n_estimators=500)

In [33]:
preds = rf.predict(X_test)
mean_squared_error(y_test, preds, squared = False)

23.23578635431047

In [34]:
df.groupby(['control', 'treatment']).agg({'percentChange': ['mean']})

                                          percentChange
                                                   mean
control              treatment
Conservation tillage No tillage               15.965068
                     Zonal tillage             7.774944
Conventional tillage Conservation tillage      1.711301
                     No tillage               10.461808
                     Zonal tillage             6.381040
Zonal tillage        Conservation tillage      2.688333
                     No tillage                1.990366